[ClassVersion("1.0.0"), FriendlyName("cOctopusServerOktaAuthentication")]
class cOctopusServerOktaAuthentication : OMI_BaseResource
{
  [Key, Description("Name of the Octopus Server instance")] string InstanceName;
  [Write, Required] boolean Enabled;
  [Write] string Issuer;
  [Write] string ClientId;
};
