[ClassVersion("1.0.0"), FriendlyName("cOctopusServerSpace")]
class cOctopusServerSpace : OMI_BaseResource
{
  [Required, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Key] string Name;
  [Write] string Description;
  [Write, Required] string Url;
  [Write] string SpaceManagersTeamMembers[];
  [Write] string SpaceManagersTeams[];
  [Write, EmbeddedInstance("MSFT_Credential")] string OctopusCredentials;
  [Write, EmbeddedInstance("MSFT_Credential")] string OctopusApiKey;
};
